# The name of the App #
name: ci-cd-test
# Some general settings for the project #
options: 
    createIntermediateGroups: true
    indentWidth: 4
    tabWidth: 4
    bundleIDPrefix: "com.seven" 
    xcodeVersion: "15.0"
    # postGenCommand: pod install

targets:
    ci-cd-test:
        type: application
        platform: iOS
        # iOS version
        deploymentTarget: "15.0"
        sources:
            - path: ci-cd-test

        # settings
        settings:
            ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
            base:
                CURRENT_PROJECT_VERSION: 0
                MARKETING_VERSION: 1.0.0
                # Bundle ID
                PRODUCT_BUNDLE_IDENTIFIER: com.seven.pets
                # Team ID
                DEVELOPMENT_TEAM: "NMM9F9QK67"
                GENERATE_INFOPLIST_FILE: NO
                # capability
                # CODE_SIGN_ENTITLEMENTS: # ci-cd-test/ci-cd-test.entitlements
                INFOPLIST_FILE: ci-cd-test/Info.plist
        scheme:
            testTargets:
                - ci-cd-testTests
    # Test target
    ci-cd-testTests:
        type: bundle.unit-test
        platform: iOS
        deploymentTarget:
            iOS: "15.0"
        sources:
            - path: ci-cd-testTests
        dependencies:
            - target: ci-cd-test

