# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: macos-latest

    # run on device
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # - name: Build & Test
      #   run: xcodebuild clean build test -workspace ci-ct-test.xcworkspace -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0'
      # - name: Build
      #   run: swift build
      # - name: Run tests
      #   run: swift test
      
